### PR TITLE
migrate to @ungap/event-target

### PR DESCRIPTION
**Pull request by Hypnosphi**
from NPM warning:

```
npm WARN deprecated event-target@0.1.0: improved, moved, and maintained as @ungap/event-target
```

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@princed can you please review

**Review by princed — APPROVED** [review]
Thank you Filipp! 
I couldn't even dream about getting PRs in this repo 😛

**Comment by princed** [comment]
Published as `2.0.0`

**Comment by Hypnosphi** [comment]
OK, here's a problem: `@ungap/event-target` includes both `cjs` and `esm` builds (`main` and `module` fields in `package.json`. So when I use `storage-mock` with webpack, it picks the `esm` build. Possible solutions I see:

1. ```js
   var eventTargetExports = require('@ungap/event-target');
   var EventTarget = eventTargetExports.default || eventTargetExports
    ```
2. Move `storage-mock` sources to ES modules, and add a prepublish script compiling them to commonjs
3. Same as 2, but also share the sources as `module` field

Which one do you prefer?

**Comment by princed** [comment]
Oh 🙈 

Whichever seems the right thing™️ to you.

**Pull request merged**
